### ISSUE TITLE
I am new to pyiwn. I am install pyiwn via pip.iwn=pyiwn.IndoWordNet() comment give the ERROR:'charmap' codec can't decode byte 0x8d in position 13: character maps to <undefined>.please help me as soon as possible.

### ISSUE THREAD

**Issue by mahemicro96** [riteshpanjwani/pyiwn#14]
>>iwn = pyiwn.IndoWordNet()
2019-10-04:13:09:42,355 INFO     [iwn.py:43] Loading hindi language synsets...
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    iwn = pyiwn.IndoWordNet()
  File "C:\Users\mahe\AppData\Local\Programs\Python\Python37\lib\site-packages\pyiwn\iwn.py", line 45, in __init__
    self._synset_df = self._load_synset_file(lang.value)
  File "C:\Users\mahe\AppData\Local\Programs\Python\Python37\lib\site-packages\pyiwn\iwn.py", line 51, in _load_synset_file
    synsets = list(map(lambda line: self._load_synset(line), f.readlines()))
  File "C:\Users\mahe\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 13: character maps to <undefined>

**Comment by mahemicro96** [comment]
finally i found the solution.i add the encoding="utf-8" to line 50 in iwn.py .(i.e)replaced by f = open(filename,encoding='utf-8') 
File "C:\Users\mahe\AppData\Local\Programs\Python\Python37\lib\site-packages\pyiwn\iwn.py", line 51, in _load_synset_file
